// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activity = {
  id: string;
  user_id: string;
  name: string;
  description: string;
  calories: number;
  duration: string | null;
  created_at: string;
};
