// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Goal = {
  user_id: string;
  calories_consumed: number | null;
  calories_burned: number | null;
  active_time_s: number | null;
};
