// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Goal } from "./Goal";
import type { UserSetting } from "./UserSetting";

export type Signup = {
  name: string;
  email: string;
  password: string;
  goals: Goal | null;
  settings: UserSetting | null;
};
