# Nix formatters
[formatter.nix-alejandra]
command = "alejandra"
options = []
includes = [ "*.nix" ]

[formatter.nix-deadnix]
command = "deadnix"
options = []
includes = [ "*.nix" ]

# Rust formatter
[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

# TypeScript/JavaScript formatter
[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.js",
  "*.jsx",
  "*.ts",
  "*.tsx",
  "*.json",
  "*.html",
  "*.css",
  "*.scss",
  "*.md"
]
