// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Goal = {
  id: string;
  user_id: string;
  consumed: number;
  burned: number;
  created_at: string;
};
